### ISSUE TITLE
Escaped html name is shown in the dropdown

### ISSUE THREAD

**Issue by TomoTsuyuki** [Syxton/moodle-block_massaction#103]
When a topic name includes something character which needs to be escaped in the html (e.g. "&", ">", etc.), the topic dropdown in the mass action uses escaped name (e.g. "&amp;", "&gt;", etc).

![massaction-dropdown-with-special-chars](https://github.com/Syxton/moodle-block_massaction/assets/54526084/1d1e030d-6e04-4709-a18f-c1f7c1812ca3)

**Comment by Syxton** [comment]
merged in both branches.  Thank you for your work on this!
