### ISSUE TITLE
Let moodle administrators copy to any course

### ISSUE THREAD

**Issue by cdipe** [Syxton/moodle-block_massaction#104]
When copying to another course, one can only find courses that one is added to. It would be great if moodle admins on category level could find and copy to any course in that / those category(ies), without being added to the courses.

**Comment by PhMemmel** [comment]
You can do that, just use the related admin setting. But care, depending on how many courses your site has, this can be a performance issue

**Comment by cdipe** [comment]
@PhMemmel thank you! I thought that setting would apply to teachers as well, but now I see that it works as I wanted :)

**Comment by PhMemmel** [comment]
It does apply to teachers as well. Teachers just do not have the necessary capabilities in the target course if they are not enrolled, so yes, admins will see all courses and teachers will still only see the ones they are enrolled in.

**Comment by cdipe** [comment]
@PhMemmel that’s just the way it should work, I think 👍🏻 I misunderstood the text by the setting as would give any role that can edit a course permission to find and export to any course.
