### ISSUE TITLE
export to AMOS failure

### ISSUE THREAD

**Issue by Syxton** [Syxton/moodle-block_massaction#11]
Error: AMOS threw exception mlang_parser_exception: Error: Expected T_CONSTANT_ENCAPSED_STRING array item value at line 70

**Comment by PhMemmel** [comment]
Looks like `<<<EOB` syntax is not supported

**Comment by PhMemmel** [comment]
Will let you know if adding the lang strings for my language worked as soon as they are available in AMOS

**Comment by PhMemmel** [comment]
I successfully submitted the German lang strings via AMOS, waiting for approval by the German lang pack maintainers.
