### ISSUE TITLE
Incompatibility with mod_subsection

### ISSUE THREAD

**Issue by PhMemmel** [Syxton/moodle-block_massaction#125]
Moodle 4.5 introduced the ability to create subsections in a course by using mod_subsection.

As soon as a course contains a subsection block_massaction stops working: You can select an activity. When clicking an action you will receive a JS error:

![grafik](https://github.com/user-attachments/assets/978471ad-f2d4-47ea-bd08-d402425b504e)

Interestingly enough it still works if a course does not contain a subsection.

**Comment by Syxton** [comment]
@PhMemmel began the dev 4.5 branch.  #133
Right now all it does is ignore subsection modules.  We need to resort the list so that section a, subsection of a, section b, section c, etc is the order.  Currently subsections are placed at the bottom of the list.

**Comment by Syxton** [comment]
Fix merged to master.  Compatible with 4.4 and 4.5
