### ISSUE TITLE
Not working on MacOS Safari and Chrome on MacOS

### ISSUE THREAD

**Issue by ctam** [Syxton/moodle-block_massaction#19]
On MacOS (Catalina and Big Sur), it doesn't work at all on Safari. On Chrome, it behaves strangely. It works OK on Firefox.

It has no problem on Windows 10, using Firefox, Chrome and Edge.

When you select a section from the menu, and then click Deselect All, the menu resets to the top option — "Select all in a section."  I've also noticed that the menu options, when first loading the page, don't appear to populate the menu that quickly.

**Comment by PhMemmel** [comment]
Hi @ctam,

could you please be a bit more specific about what "behaving strangely" means for Chrome?

Could you maybe provide a video or some Screenshots? Are the items in the selected section being selected when the drop down snaps back?

**Comment by ctam** [comment]
Hi @PhMemmel,

We believe this bug is similar to [MDL-69292](https://tracker.moodle.org/browse/MDL-69292).  'The Atto editor issue was caused by a mismatch between the expectations of the accessibility focuslock code and the events in Safari and Chrome on the Mac. So it is almost certainly the same (or a very similar) infinite-loop callstack-exceeded thing going on.'

I will try to produce some screenshots.  It does not seem to related to any specific course format.  We are on Moodle 3.11.6 (2021051706) and we are seeing this issue on Mass Actions block v6.0.0 but not on any earlier version.

**Comment by PhMemmel** [comment]
@Syxton Would this also address the "strange" behavior on Chrome or is this a different issue?

**Comment by PhMemmel** [comment]
@Syxton I opened a PR #20 with your suggested change. Can you please test this?

Also @ctam Are you able to test this PR #20 (Branch https://github.com/Syxton/moodle-block_massaction/tree/Fix_safari_compatibility) and let me know if this improves the behavior of Chrome and/or Safari? Unfortunately, I don't have access to any MacOS system, so I'm dependent on your feedback.

If this doesn't solve the infinite loop thing I definitely will need some further debugging information like browser console output to get an idea of what's happening there. To be honest I do not completely understand what's the problem about the mentioned moodle issue is/was

**Comment by PhMemmel** [comment]
@ctam Is the section selection the only bug you are experiencing?

And I just realized I overlooked one thing in your first post:
Yes, the section select dropdown (and BTW also the other ones) are being loaded a bit later on which is on purpose, because this dropdown will also update itself on course changes (dynamic renaming of sections without reloading the page, disabling sections when the last module is moved out of it etc.). Due to technical limitations there has to be a small timeout. In the rework for moodle 4.0 it will load quickly as expected. Also the (re)creation of the checkboxes will be quicker.

**Comment by Syxton** [comment]
@ctam This has now been fixed #20   Thank you for reporting!

**Comment by ctam** [comment]
Yes, I can test it.  Will keep you posted.

**Comment by ctam** [comment]
Yes, the fix works.  It's working on MacOS Chrome and Safari now!

**Comment by PhMemmel** [comment]
Awesome! Thank you for both the report and the feedback!
