### ISSUE TITLE
AMOS not picking up lang string of latest release

### ISSUE THREAD

**Issue by PhMemmel** [Syxton/moodle-block_massaction#48]
Hi @Syxton,

AMOS didn't pick up the added lang string of the newest release for a reason I do not understand, so it cannot be translated. Do you have any idea why? Or can you maybe trigger this manually/again somehow?

**Comment by PhMemmel** [comment]
Ah, my bad. Didn't remember that string concatenation is not allowed in lang files. Sorry and thx for the fix!

**Comment by Syxton** [comment]
@PhMemmel  No problem.  Should be good now.

**Comment by PhMemmel** [comment]
Can confirm, strings already loaded into AMOS database. Thanks again!
