### ISSUE TITLE
Checkbox unavailable in Moodle 3.10, Moove Theme. 

### ISSUE THREAD

**Issue by PrabhashChamara** [Syxton/moodle-block_massaction#50]
![image](https://user-images.githubusercontent.com/20293518/181449831-acc6a5f9-a4a5-4ebc-9211-692823f5dc3f.png)

**Comment by PhMemmel** [comment]
Could you please provide the output of the browser dev console? Does it work in boost theme for you?

**Comment by jfkken42** [comment]
@PhMemmel 
![image](https://user-images.githubusercontent.com/119411716/204594700-ec8c95d3-00fb-4945-9653-f957ef5df5f9.png)
