### ISSUE TITLE
Duplications "in background" but don't complete

### ISSUE THREAD

**Issue by bgoodlin01** [Syxton/moodle-block_massaction#51]
I've tried duplicating the contents of one section into another using the pull-down menu, and selecting the items in a section and simply clicking the "Duplicate" link.  In both cases, a message comes up saying "The action you demanded is being executed in the background. You can continue your work while waiting for it to finish."  Ten minutes later, and it still hasn't finished.  The section I'm trying to duplicate has only five items in it, so it seems unlikely that it would take so long do duplicate -- all the other actions (moving, deleting, etc) happened immediately.

**Comment by bgoodlin01** [comment]
Looks like they weren't running.  They're running now, and the issue has resolved.  Thanks!

**Comment by bgoodlin01** [comment]
Is there a threshold for when cron is used for duplications?  Just poking around, it seems that groups of 1 to 5 items can be duplicated without involving cron, but more than 5 requires a cron task.  I'm making a tutorial for my users and I want to let them know when to expect a wait and when not to.  (On our server, using cron means a wait of up to three minutes.)

**Comment by PhMemmel** [comment]
Hi @bgoodlin01: Yes, this can be configured in the admin settings of the block. It also can be turned off completely. The default value is 5.

**Comment by bgoodlin01** [comment]
Thanks!  I'll talk to our admin.
