### ISSUE TITLE
Localisation missing in drop down menues

### ISSUE THREAD

**Issue by cdipe** [Syxton/moodle-block_massaction#63]
We have translated all language strings to Swedish, but the localisation is not working in the drop down menues. Using Mass Actions 2022041703 in Moodle 3.11.10
<img width="279" alt="image" src="https://user-images.githubusercontent.com/14754240/197727510-4e5f5b19-06f0-490a-b578-7d3a0ddb2fff.png">

**Comment by PhMemmel** [comment]
Hi @cdipe, from code perspective the strings are properly localized. This has to be an issue with missing Amos strings. I just double checked on Amos and for language "sv" I cannot find any localized language strings at all. Where exactly did you translate them?

**Comment by Syxton** [comment]
@cdipe Can you purge Moodle string cache?  Maybe the strings didn't get updated.  Admin->Developement->Purge caches

**Comment by cdipe** [comment]
@Syxton thanks, that solved it!
