### ISSUE TITLE
Bug: invalidqueryparam when trying to select target course

### ISSUE THREAD

**Issue by PhMemmel** [Syxton/moodle-block_massaction#66]
In some cases I receive an error while trying to select a course (feature "Duplicate to another course"):

![grafik](https://user-images.githubusercontent.com/65113153/199778818-7ac7b09a-00b2-49aa-b858-b81e1ba09ed3.png)

This happens if the user is not enrolled in the source course and at the same time has no target course available, so a very specific edge case. But I'm not 100% sure if this is the only case where this problem occurs. This only seems to happen if the `block_massaction` config key `limittoenrolled` is enabled.

Stack trace with debugging enabled:
```
Error code: invalidqueryparam
* line 945 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1206 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->fix_sql_params()
* line 786 of /lib/datalib.php: call to mysqli_native_moodle_database->get_recordset_sql()
* line 1662 of /course/classes/category.php: call to get_courses_search()
* line 2601 of /course/externallib.php: call to core_course_category::search_courses()
* line 261 of /lib/externallib.php: call to core_course_external::search_courses()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

Error code: invalidqueryparam
* line 945 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1206 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->fix_sql_params()
* line 786 of /lib/datalib.php: call to mysqli_native_moodle_database->get_recordset_sql()
* line 1662 of /course/classes/category.php: call to get_courses_search()
* line 2601 of /course/externallib.php: call to core_course_category::search_courses()
* line 261 of /lib/externallib.php: call to core_course_external::search_courses()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```

**Comment by Syxton** [comment]
@PhMemmel Interesting.  Did you have to manually enter the URL since you weren't enrolled in the source course?

**Comment by PhMemmel** [comment]
Yes, I experienced this as admin user while testing (no course enrolments, but access to all courses). I even think this could be a moodle core bug, but have not have time yet to dig deeper.

**Comment by PhMemmel** [comment]
I retested again and found the reason: It is a code adaption in our own code, so this bug only occurs in our own instance. Thank you very much for having a look and providing feedback. Closing this as "fixed" :-)
