### ISSUE TITLE
Preparation for moodle 4.2

### ISSUE THREAD

**Issue by PhMemmel** [Syxton/moodle-block_massaction#71]
I ran the unit tests and behat tests against current master (which is moodle 4.2 beta) with latest versions of format_tiles, format_grid and format_onetopic being installed.

Everything looks good so far. So I think it's safe to declare block_massaction as compatible for moodle 4.2.

As in the meantime there are moodle 4.0 (and above) compatible version of format_tiles, format_grid and format_onetopic I suggest to merge #29, #32, #33.

@Syxton Please declare block_massaction compatible with moodle 4.2 as soon as this is available in the plugin directory.

I know with the new bulk activity course actions introduced in moodle 4.2 some of block_massaction's features now are redundant, but it's still worth using it for duplicating activities into other courses for example. In the long run we should consider substituting some of the basic features which are now covered by moodle core by features unique to block_massaction.

**Comment by Syxton** [comment]
@PhMemmel I have merged #29, #32, and #33.  However, in the plugins database they do not yet have 4.2 as a selectable supported version.  As soon as it becomes available I'll add the new 7.1.2 release and add 4.2 support to the 7.1.1 release.

**Comment by PhMemmel** [comment]
Yes, I know, it's not available yet on moodle.org, but will be soon. As soon as it is, we also should add the MOODLE_402_STABLE branch to GHA and eventually bump the minimum database versions for 4.2. Thank you very much in advance.

BTW: I also tested against vs. format_topcoll. Currently tests are failing, but this is an issue of format_topcoll itself which has already been reported, but not been fixed yet: https://github.com/gjb2048/moodle-format_topcoll/issues/128

**Comment by Syxton** [comment]
4.2rc1 is released so I have now updated the plugins to be 4.2 compatible

**Comment by PhMemmel** [comment]
Awesome, thank you very much. One more question: In Moodle 4.2 we now have two separate checkboxes when bulk actions are enabled. Should we split up a 4.2 branch and try to use the checkboxes provided by moodle itself?

**Comment by Syxton** [comment]
@PhMemmel Yes, we should sense whether the moodle checkboxes already exist before we decide to add our own.  Eventually the course formats will support the bulk editing and we will be out of the checkbox creating business. :) The Moodle checkboxes also have a cool feature that you can select 1 and hold Shift and hold another and it selects between the checkbox.
