### ISSUE TITLE
7.1.2 Upgrade error

### ISSUE THREAD

**Issue by durzo** [Syxton/moodle-block_massaction#73]
Moodle 4.1.3 with postgres database, upgrading to plugin version 7.1.2 throws this exception:
```
-->block_massaction
Default exception handler: Exception - Attempt to assign property "value" on bool Debug: 
Error code: generalexceptionmessage
* line 84 of /blocks/massaction/db/upgrade.php: Error thrown
* line 42 of /blocks/massaction/db/upgrade.php: call to block_massaction_add_supported_format()
* line 1113 of /lib/upgradelib.php: call to xmldb_block_massaction_upgrade()
* line 679 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Exception - Attempt to assign property "value" on bool !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 84 of /blocks/massaction/db/upgrade.php: Error thrown
* line 42 of /blocks/massaction/db/upgrade.php: call to block_massaction_add_supported_format()
* line 1113 of /lib/upgradelib.php: call to xmldb_block_massaction_upgrade()
* line 679 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!
```

**Comment by PhMemmel** [comment]
Thank you @durzo for opening this issue. Could you maybe go to the block_massaction Admin settings and manually select/deselect one of the course formats, retry to upgradeand report here if this solves the issue for you? This would confirm what I think the issue is here.

**Comment by durzo** [comment]
We cant access the site because there is an upgrade pending. We rolled back to 7.1.1
Should we perform the steps on 7.1.1  and then try 7.1.2 again?

**Comment by PhMemmel** [comment]
I linked a pull request which theoretically should fix the issue. However, the reason you experienced this, was, that you did not accept the default settings when these settings first were introduced. So no config key has been saved to your database which should not be the case if you just accept the default settings. Unfortunately, the upgrade code has not been that safe to consider this special case, sorry for that :-)

I did not carefully test this patch, but it works for me locally. If you have a testing environment, feel free to apply the patch and see if you can upgrade your site. Feedback of course very welcome in case also other users are experiencing this issue.
