### ISSUE TITLE
Database case sensitivity breaks plugin (MSSQL)

### ISSUE THREAD

**Issue by mikehenry1979-bah** [Syxton/moodle-block_massaction#77]
The id column of course_modules is lowercase and the plugin does not work in our environment unless the start of line 69 in classes/massactionutils.php is changed from 'ID IN ( to 'id IN (

**Comment by PhMemmel** [comment]
Thank you for reporting this and also providing the solution.

This is most likely a typo that did not matter for most DMBS, so did not cause any issues so far. I put your suggestion to fix this into a pull request. As I do not have a MSSQL database for testing, could you please confirm again this fixes the issue?

**Comment by mikehenry1979-bah** [comment]
It does fix the issue for MSSQL, we have been using it on our production site since installation of the plugin. I understand in Postgres that case sensitivity is only enforced when selecting a column if double quotes are used.
