### ISSUE TITLE
Add a callback to let other plugins to limit sections allowed to move activities to

### ISSUE THREAD

**Issue by dmitriim** [Syxton/moodle-block_massaction#86]
We have a case when a client is using a custom course format. As part of this format some of the sections are populated automatically using external data and no activities are allowed to added to those sections. 

We are proposing to extend a functionality of the block and implement a callback that will allow course formats declare a list of sections that are not allowed for moving/duplicating activities to inside a course or when moving to another course.

**Comment by TomoTsuyuki** [comment]
I made PR #92 for this issue.
Please review and merge if it's ok.

**Comment by Syxton** [comment]
merged in both branches. Thank you for your work on this!
