### ISSUE TITLE
Do not display block's content if a user doesn't have block/massaction:use

### ISSUE THREAD

**Issue by dmitriim** [Syxton/moodle-block_massaction#87]
There is a capability block/massaction:use that let users to use the block, however it's only checked in one spot https://github.com/Syxton/moodle-block_massaction/blob/master/action.php#L42 

Would be much better UX if we check this capability before even rendering content so users without require permissions don't event see block.

**Comment by TomoTsuyuki** [comment]
I made PR #93 for this issue.
Please review and merge if it's ok.

**Comment by Syxton** [comment]
merged in both branches.  Thank you for your work on this!
