### ISSUE TITLE
A new setting to enable disable/enable parts of the functionality

### ISSUE THREAD

**Issue by dmitriim** [Syxton/moodle-block_massaction#88]
We have a case when a client wants to allow some part of the functionality of the block, but not another. E.g. allow to move inside a course, but not to another course and etc. 

![image](https://github.com/Syxton/moodle-block_massaction/assets/4626431/ed567ea1-bdfa-478e-a245-2a03e5422114)

That could be done in two ways:

1. Use extra capabilities for each part of the functionality 
2. Use add extra global settings for each pat of the functionality 

Capability part of much more flexible as you can configure it for specific roles. E.g. teaches can only move inside courses, but admin can do everything. 

I saw that functional already hidden behind core capabilities, but this is not flexible enough.

**Comment by TomoTsuyuki** [comment]
It looks more options for current version

![image](https://github.com/Syxton/moodle-block_massaction/assets/54526084/1c93eb7b-cf29-4ace-ae27-4a346d6e688e)

**Comment by PhMemmel** [comment]
Yes and no. There are 2 more for this version. Which are shown however, is based on capabilities and for example, if the course format used supports indentation. That's why there is a big difference in the both screenshots.

**Comment by TomoTsuyuki** [comment]
I made PR #94  for this issue.
Please review and merge if it's ok.

**Comment by Syxton** [comment]
merged in both branches.  Thank you for your work on this!
